# Generated by Django 4.0.3 on 2022-03-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faketwit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
