# Generated by Django 4.0.3 on 2022-03-12 07:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faketwit', '0009_relations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relations',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='relations',
            unique_together={('followed', 'follower')},
        ),
    ]
